// vue/src/App.vue
<template>
    <DxSwitch 
        :value="false"
        :width="80"
        :rtlEnabled="true"
        :hint="hint_message"
        @value-changed="onValueChanged($event)"
    > </DxSwitch>
</template>

<script>
import "devextreme/dist/css/dx.light.css";
import { DxSwitch } from "devextreme-vue/switch";
import notify from "devextreme/ui/notify";

export default {
    components: {
        DxSwitch
    },
    data() {
        return {
            hint_message: "Click to switch on",
        };
    },
    methods: {
        onValueChanged(e) {
            this.hint_message = e.value ? "Click to switch off" : "Click to switch on";
            const state_label = e.value ? "ON" : "OFF";
            notify(`The component is switched ${state_label}`);
        }
    }
}
</script>

// react/src/App.js
import React, { useState, useCallback } from "react";
import "devextreme/dist/css/dx.light.css";

import { Switch } from "devextreme-react/switch";
import notify from "devextreme/ui/notify";

function App() {
    const [hint_message, setHintMessage] = useState("Click to switch on");

    const onValueChanged = useCallback((e) => {
        const message_text = e.value ? "Click to switch off" : "Click to switch on";
        const state_label = e.value ? "ON" : "OFF";
        setHintMessage(message_text);
        notify(`The component is switched ${state_label}`); 
    }, []);
    
    return (
        <Switch 
            value={false}
            width={80}
            rtlEnabled={true}
            hint={hint_message}
            onValueChanged={onValueChanged}
        />
    );
}

export default App;
